### ISSUE TITLE
It takes too much time for reading large tree file.

### ISSUE THREAD

**Issue by y9c** [YuLab-SMU/treeio#12]
When parsing large tree file (>10k  leaves) in NHX format, it takes a very long time in running this command.

```r
read.nhx("./test.nhx")
```

I kill it after several minutes, and don't known how many times it will takes.

The file is in the correct format, cause python package ETE3 can parse this file within seconds.

I also tried reading the same NHX file with newick parser, `read.newick`. The file is turn into R object successfully, ~~but failed to be rendered in `ggtree` package. This is the error message from ggtree.~~
```
restarting interrupted promise evaluationinternal error -3 in R_decompress1Error in fortify.phylo(data, ...) : 
  lazy-load database '/usr/local/lib/R/site-library/ape/R/ape.rdb' is corrupt
```

---

UPDATE:

After reinstall `ape` and `ggtree` package, `R_decompress1Error` gone. The only problem here is that NHX parser not works properly.

**Comment by yech1990** [comment]
testing data:

```python
from ete3 import Tree
t2 = Tree()
t2.populate(20_000)
t2.write(format=8, outfile="./test.nhx", features=["dist", "support"])
```


[test.zip](https://github.com/GuangchuangYu/treeio/files/2452793/test.zip)
