### ISSUE TITLE
could not find function "read.mega"

### ISSUE THREAD

**Issue by haruosuz** [YuLab-SMU/treeio#32]
I got this error message as follows:
```r
> BiocManager::install("treeio")
> packageVersion("treeio")
[1] ‘1.8.2’

> devtools::install_github("GuangchuangYu/treeio")
> packageVersion("treeio")
[1] ‘1.11.2’

# https://yulab-smu.github.io/treedata-book/chapter1.html
# 1.3.2.2 Parsing MEGA output
> file <- system.file("extdata/MEGA7", "mtCDNA_timetree.nex", package = "treeio")
> read.mega(file)
Error in read.mega(file) : could not find function "read.mega"
```

**Comment by brj1** [comment]
Install the github version

```r
library(devtools)
install_github("YuLab-SMU/treeio")
```

**Comment by haruosuz** [comment]
#install.packages("vroom")
file <- system.file("extdata/MEGA7", "mtCDNA_timetree_tabular.txt", package = "treeio")
read.mega_tabular(file) 

Thank you. Could you update the github page?
https://github.com/YuLab-SMU/treeio/blob/master/README.md#arrow_double_down-installation
``` r
## install.packages("devtools")
devtools::install_github("GuangchuangYu/treeio")
```

`read.mega(file)` worked after `devtools::install_github("YuLab-SMU/treeio", force = TRUE)`.
`read.mega_tabular(file)` worked after `install.packages("vroom")`.

**Comment by GuangchuangYu** [comment]
`read.mega` and `read.mega_tabular` are available in current release branch, <https://www.bioconductor.org/packages/treeio>. 

You don't need to install github version to have these functions.
