### ISSUE TITLE
tree::offspring returns empty table with self_include = T

### ISSUE THREAD

**Issue by daniilprigozhin** [YuLab-SMU/treeio#33]
I ran the following code:

```
library("treeio")
file <- system.file("extdata/BEAST", "beast_mcc.tree", package="treeio")
beast <- read.beast(file)
beast
tb_beast <- as_tibble(beast)
offspring(tb_beast,1,self_include = T)
```
  

I would expect a non-empty table that would include node number 1, since self_include = T.
Instead, get:

A tibble: 0 x 17

I realize this is a result of calling offspring on a tip, but would still like for it to work as it would for internal nodes.

Thank you.

**Comment by brj1** [comment]
I cannot reproduce this with the latest version of ggtree (release or dev). Try using `self_include = TRUE` not `self_include = T`, since `T` can be reset and `TRUE` cannot.

**Comment by daniilprigozhin** [comment]
Restarting R and updating packages fixed it. Thanks for a prompt response.
