### ISSUE TITLE
Reading RAxML-ng trees - coerce phyla to data.frame

### ISSUE THREAD

**Issue by heather340** [YuLab-SMU/treeio#35]
Hi! I recently shifted from raxml to raxml-ng, so now I am having issues with the code I built previously with these great packages. 

I am reading trees using read.tree instead of read.raxml as was suggested in another post, but I get the following issue (file included below as a .txt)
> nex <- ("raxml_UCE_75p_mem_names.raxml.supportFBP")
> tree <- read.tree(nex)
> tree$node.label
 [1] ""    "50"  "57"  "88"  "43"  "72"  "47"  "100" "100" "56"  "100" "100" "100" "100" "100" (etc)
> tree$tip.label
 [1] "Ireland_I46"                   "Norway_N117"                   "Norway_N97"                    "Norway_N4"                    
 [5] "Ireland_I111"                  "Alaska_AL28"                   "Alaska_AL16"                     (etc)
> ggtree(tree)
Error in as.data.frame.default(value, stringsAsFactors = FALSE) : 
  cannot coerce class ‘"phylo"’ to a data.frame

[raxml_UCE_50p_names.raxml.supportFBP.txt](https://github.com/YuLab-SMU/treeio/files/4664621/raxml_UCE_50p_names.raxml.supportFBP.txt)

Any suggestions would be appreciated!

Thanks, 
Heather

**Comment by GuangchuangYu** [comment]
can't reproduce your issue

[image: image.png]

**Comment by GuangchuangYu** [comment]
can't reproduce your issue


![](https://user-images.githubusercontent.com/626539/82973048-0bb85100-a009-11ea-81e9-df075fe09de2.png)

**Comment by brj1** [comment]
You probably need to update your R packages. Try

```R
update.packages(ask=FALSE)
BiocManager::install("ggtree")
```

**Comment by heather340** [comment]
Looks like that is likely it. I was able to figure out a workaround with another package, but this will be good to have fixed moving forward :)

Thanks for the help!
