### ISSUE TITLE
error while reproducing manual example

### ISSUE THREAD

**Issue by xbarvazx** [YuLab-SMU/treeio#37]
Hi,

I am trying to reproduce an example from the manual (chapter 5.2.2) for running `geom_hilight` 
I am using treeio 1.10.0 and ggtree 2.0.4 on Rstudio

```
x <- read.nhx(system.file("extdata/NHX/ADH.nhx", package="treeio"))
ggtree(x) + geom_hilight(mapping=aes(subset = node %in% c(10, 12), fill = S)) +
    scale_fill_manual(values=c("steelblue", "darkgreen"))

```
But I am getting this error
```
Error in structure(list(node = node, fill = fill, alpha = alpha, extend = extend,  : 
  argument "node" is missing, with no default
```
I noticed that you mentioned to try use ape::root.phylo over treeio::root.phylo but I do not understand how.

Best,
Raz

**Comment by xiangpin** [comment]
The version of `ggtree` on your platfrom is too old. If you want to use `geom_hilight` which supports aesthetic, you need update [`ggtree`](https://www.bioconductor.org/packages/release/bioc/html/ggtree.html).

**Comment by xbarvazx** [comment]
Hi,
Thanks for the answer. I updated ggtree to 2.2.3 but I am still getting the same error. 
I uploaded `ggtree` first and then `ape` but I still see the message:
```
Registered S3 method overwritten by 'treeio':
  method     from
  root.phylo ape 
```

**Comment by xiangpin** [comment]
This message is no error or warning. You can ignore it.

**Comment by xbarvazx** [comment]
Ok.
But I still get no plot using the example after I upgraded ggtree to v.2.2.3
```
x <- read.nhx(system.file("extdata/NHX/ADH.nhx", package="treeio"))
ggtree(x) + geom_hilight(mapping=aes(subset = node %in% c(10, 12), fill = S)) +
    scale_fill_manual(values=c("steelblue", "darkgreen"))
```
and getting the same error as before
```Error in structure(list(node = node, fill = fill, alpha = alpha, extend = extend,  : 
  argument "node" is missing, with no default```

What could be the problem

**Comment by xiangpin** [comment]
I don't think you have updated it. The error is from old version. please use `packageVersion("ggtree")` to check the version.

**Comment by xbarvazx** [comment]
```
> packageVersion("ggtree")
[1] ‘2.2.3’
```

**Comment by xiangpin** [comment]
Ok, The new version hasn't been push to bioconductor. You can update it by `github`

**Comment by xbarvazx** [comment]
Works!
Thanks a lot,
