### ISSUE TITLE
Issue with function write.beast: not writing multiple BEAST trees

### ISSUE THREAD

**Issue by tiagorsimoes** [YuLab-SMU/treeio#39]
Hello Dr. Yu,

Thanks for this incredible package! The function read.beast allows me to read either single (class: treedata) or multiple BEAST trees (treedata list). However, the function write.beast only allows me to export a single BEAST tree, and not multiple BEAST trees. When I try to export an object with multiple BEAST trees, I get the following error:

Error in UseMethod("Ntip") : 
  no applicable method for 'Ntip' applied to an object of class "treedataList"

The write.nexus from ape allows me to export either a single or multiple standard formatted trees. As the write.beast is based on the latter, I believe this may be possible to fix, but I wanted to reach out to you to ask how to modify the function.

Best regards,

Tiago

**Comment by GuangchuangYu** [comment]
not supported yet.

**Comment by tiagorsimoes** [comment]
Thanks for the feedback. Is it possible to request its inclusion?

**Comment by sanderdebacker** [comment]
Three years later and this seems still not implemented. 
It would be an extremely useful feature! Please consider adding this :-)

**Comment by GuangchuangYu** [comment]
supported now.

For `Ntip` method of `treedataList` object, you can use `Ntip(x[[1]])`, and will be supported to directly use `Ntip(x)` in the future release version of the `tidytree`.
