### ISSUE TITLE
Regarding "read.beast" function 

### ISSUE THREAD

**Issue by avvypaks** [YuLab-SMU/treeio#43]
Hi, I am trying to run the following script: https://raw.githubusercontent.com/taming-the-beast/FBD-tutorial/master/scripts/plot_geoscaled_tree.R where "phyloch" package is no longer giving me the function "read.beast".

I have used "treeio" instead to run my annotated beast tree through "read.beast" function. But the following code `t$root.time <- t$height[1]`  is showing the error : 
"Error in t$height : $ operator not defined for this S4 class".
 Can you help me out with a solution?

**Comment by brj1** [comment]
`treeio::read.beast()` returns a `teedata` object which does not have a `$height` property. Instead node data are stored in the `@data` slot. To get the height of the root you can use the code:

```R
tree@data[tree@data$node == Ntip(tree@phylo), "height"]
```

The `read.beast()` function from `phyloch` returns a tree with node data appended to it keeping it as a `phylo` object adding a `$height` property among others. I believe that if you want to use `treeio`'s `read.beast()` function you will need to modify a lot more of your code.

**Comment by GuangchuangYu** [comment]
```r
> file <- system.file("extdata/BEAST", "beast_mcc.tree", package="treeio")
> x <- read.beast(file)
> x[,"height"]
# A tibble: 29 x 1
   height
    <dbl>
 1   0   
 2   3   
 3   9.47
 4  26   
 5  34.9 
 6  33   
 7  30   
 8  21   
 9  17   
10  18   
# … with 19 more rows
> x[rootnode(x),"height"]
# A tibble: 1 x 1
  height
   <dbl>
1     19
> x[["height"]]
  height1   height2   height3   height4   height5   height6   height7   height8 
 0.000000  3.000000  9.470517 26.000000 34.892481 33.000000 30.000000 21.000000 
  height9  height10  height11  height12  height13  height14  height15  height16 
17.000000 18.000000 16.000000 16.000000 16.848831 19.342779 20.280411 19.000000 
 height17  height18  height19  height20  height21  height22  height23  height24 
20.778557 21.000000 23.141148 18.000000 15.000000 17.000000 20.286172 21.328706 
 height25  height26  height27  height28  height29 
23.382229 26.212769 31.600266 33.615993 38.038330 
> x[["height"]][rootnode(x)]
height16 
      19 
> 
```


Using `[[` should be compatible with `phyloch`.
