### ISSUE TITLE
S3 overwrite warning in R version 4.0.3

### ISSUE THREAD

**Issue by andemexoax** [YuLab-SMU/treeio#45]
I get a warning every time I start RStudio even before any code has been executed. 
`Registered S3 method overwritten by 'treeio':
  method     from
  root.phylo ape `

I'm using ‘treeio’ version 1.15.2 with R version 4.0.3 in RStudio version Version 1.4.1103 on a Windows 10 computer.
I searched for the issue online and it appears to be package specific [problems](https://github.com/r-lib/rlang/issues/669). 

In that thread, they suggest forwarding this type of message to package authors, 

> It seems the class "foo" of your package is conflicting with the same class "foo" of package {bar}, at least for methods baz() and quux(). Since S3 classes are not namespaced, manual namespacing is required to avoid this sort of collision. Would there be any chance you could rename your class to use your package name as a prefix? It probably makes sense to do this renaming in the package with the fewest reverse dependencies, to minimize breakages.

Hopefully, it is an easy fix.

**Comment by joshua-theisen** [comment]
This error seems to have reappeared. Here is my version and platform information, along with the error:
R version 4.3.0 (2023-04-21 ucrt) -- "Already Tomorrow"
Platform: x86_64-w64-mingw32/x64 (64-bit)

Please let me know if you would prefer I submit this as a new issue. Thanks!

```
Registered S3 methods overwritten by 'treeio':
  method              from    
  MRCA.phylo          tidytree
  MRCA.treedata       tidytree
  Nnode.treedata      tidytree
  Ntip.treedata       tidytree
  ancestor.phylo      tidytree
  ancestor.treedata   tidytree
  child.phylo         tidytree
  child.treedata      tidytree
  full_join.phylo     tidytree
  full_join.treedata  tidytree
  groupClade.phylo    tidytree
  groupClade.treedata tidytree
  groupOTU.phylo      tidytree
  groupOTU.treedata   tidytree
  inner_join.phylo    tidytree
  inner_join.treedata tidytree
  is.rooted.treedata  tidytree
  nodeid.phylo        tidytree
  nodeid.treedata     tidytree
  nodelab.phylo       tidytree
  nodelab.treedata    tidytree
  offspring.phylo     tidytree
  offspring.treedata  tidytree
  parent.phylo        tidytree
  parent.treedata     tidytree
  root.treedata       tidytree
  rootnode.phylo      tidytree
  sibling.phylo       tidytree
```

**Comment by dansmith01** [comment]
@joshua-theisen, I'm getting the exact same message too. Started happening right after updating to `treeio` version 1.23.1

**Comment by wildspike** [comment]
@joshua-theisen, I'm getting the exact same message too. But I don't know why it happened.
> R.version
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          3.1                         
year           2023                        
month          06                          
day            16                          
svn rev        84548                       
language       R                           
version.string R version 4.3.1 (2023-06-16)
nickname       Beagle Scouts               
> RStudio.Version()

$mode
[1] "desktop"

$version
[1] ‘2023.9.0.463’

$long_version
[1] "2023.09.0+463"

treeio v1.24.3

**Comment by Azurelan35** [comment]
@joshua-theisen @dansmith01 @wildspike 
Hi, I wonder if any of you has a clue how to solve this issue, since I also get the same message right after I start RStudio. My R version is 4.3.1, and treeio is v1.24.3. The message is as follows:
Registered S3 methods overwritten by 'treeio':
  method              from    
  MRCA.phylo          tidytree
  MRCA.treedata       tidytree
  Nnode.treedata      tidytree
  Ntip.treedata       tidytree
  ancestor.phylo      tidytree
  ancestor.treedata   tidytree
  child.phylo         tidytree
  child.treedata      tidytree
  full_join.phylo     tidytree
  full_join.treedata  tidytree
  groupClade.phylo    tidytree
  groupClade.treedata tidytree
  groupOTU.phylo      tidytree
  groupOTU.treedata   tidytree
  inner_join.phylo    tidytree
  inner_join.treedata tidytree
  is.rooted.treedata  tidytree
  nodeid.phylo        tidytree
  nodeid.treedata     tidytree
  nodelab.phylo       tidytree
  nodelab.treedata    tidytree
  offspring.phylo     tidytree
  offspring.treedata  tidytree
  parent.phylo        tidytree
  parent.treedata     tidytree
  root.treedata       tidytree
  rootnode.phylo      tidytree
  sibling.phylo       tidytree

**Comment by Sudaraka88** [comment]
Echoing the same as previous posts:


Registered S3 methods overwritten by 'treeio':
  method              from    
  MRCA.phylo          tidytree
  MRCA.treedata       tidytree
  Nnode.treedata      tidytree
  Ntip.treedata       tidytree
  ancestor.phylo      tidytree
  ancestor.treedata   tidytree
  child.phylo         tidytree
  child.treedata      tidytree
  full_join.phylo     tidytree
  full_join.treedata  tidytree
  groupClade.phylo    tidytree
  groupClade.treedata tidytree
  groupOTU.phylo      tidytree
  groupOTU.treedata   tidytree
  inner_join.phylo    tidytree
  inner_join.treedata tidytree
  is.rooted.treedata  tidytree
  nodeid.phylo        tidytree
  nodeid.treedata     tidytree
  nodelab.phylo       tidytree
  nodelab.treedata    tidytree
  offspring.phylo     tidytree
  offspring.treedata  tidytree
  parent.phylo        tidytree
  parent.treedata     tidytree
  root.treedata       tidytree
  rootnode.phylo      tidytree
  sibling.phylo       tidytree

> sessionInfo()

R version 4.3.0 (2023-04-21)
Platform: aarch64-apple-darwin22.6.0 (64-bit)
Running under: macOS 14.0

Matrix products: default
BLAS/LAPACK: /opt/homebrew/Cellar/openblas/0.3.24/lib/libopenblasp-r0.3.24.dylib;  LAPACK version 3.11.0

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

time zone: Australia/Melbourne
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] treeio_1.24.3

loaded via a namespace (and not attached):
 [1] vctrs_0.6.4       nlme_3.1-163      cli_3.6.1         rlang_1.1.1      
 [5] purrr_1.0.2       generics_0.1.3    jsonlite_1.8.7    glue_1.6.2       
 [9] fansi_1.0.5       grid_4.3.0        tibble_3.2.1      fastmap_1.1.1    
[13] ape_5.7-1         lifecycle_1.0.3   memoise_2.0.1     compiler_4.3.0   
[17] dplyr_1.1.3       fs_1.6.3          Rcpp_1.0.11       pkgconfig_2.0.3  
[21] tidytree_0.4.5    tidyr_1.3.0       lattice_0.22-5    digest_0.6.33    
[25] R6_2.5.1          tidyselect_1.2.0  utf8_1.2.4        pillar_1.9.0     
[29] parallel_4.3.0    magrittr_2.0.3    tools_4.3.0       lazyeval_0.2.2   
[33] cachem_1.0.8      yulab.utils_0.1.0

**Comment by kashishky** [comment]
Same issue

Registered S3 methods overwritten by 'treeio':
  method              from    
  MRCA.phylo          tidytree
  MRCA.treedata       tidytree
  Nnode.treedata      tidytree
  Ntip.treedata       tidytree
  ancestor.phylo      tidytree
  ancestor.treedata   tidytree
  child.phylo         tidytree
  child.treedata      tidytree
  full_join.phylo     tidytree
  full_join.treedata  tidytree
  groupClade.phylo    tidytree
  groupClade.treedata tidytree
  groupOTU.phylo      tidytree
  groupOTU.treedata   tidytree
  inner_join.phylo    tidytree
  inner_join.treedata tidytree
  is.rooted.treedata  tidytree
  nodeid.phylo        tidytree
  nodeid.treedata     tidytree
  nodelab.phylo       tidytree
  nodelab.treedata    tidytree
  offspring.phylo     tidytree
  offspring.treedata  tidytree
  parent.phylo        tidytree
  parent.treedata     tidytree
  root.treedata       tidytree
  rootnode.phylo      tidytree
  sibling.phylo       tidytree

**Comment by TZM9882** [comment]
> Same issue
> 
> Registered S3 methods overwritten by 'treeio': method from MRCA.phylo tidytree MRCA.treedata tidytree Nnode.treedata tidytree Ntip.treedata tidytree ancestor.phylo tidytree ancestor.treedata tidytree child.phylo tidytree child.treedata tidytree full_join.phylo tidytree full_join.treedata tidytree groupClade.phylo tidytree groupClade.treedata tidytree groupOTU.phylo tidytree groupOTU.treedata tidytree inner_join.phylo tidytree inner_join.treedata tidytree is.rooted.treedata tidytree nodeid.phylo tidytree nodeid.treedata tidytree nodelab.phylo tidytree nodelab.treedata tidytree offspring.phylo tidytree offspring.treedata tidytree parent.phylo tidytree parent.treedata tidytree root.treedata tidytree rootnode.phylo tidytree sibling.phylo tidytree

hello,
I got the same issue. but it was solved with this simple works that I noticed here #109

remotes::install_github('YuLab-SMU/treeio')
