### ISSUE TITLE
read.bease fails to load NEXUS tree files with spaces in tip labels

### ISSUE THREAD

**Issue by tgvaughan** [YuLab-SMU/treeio#66]
Hi, thanks for treeio - super useful! 

I've encountered a bug with the latest version on BC.  The following should load the 3-leaf tree from 
[problem.tree.txt](https://github.com/YuLab-SMU/treeio/files/7085552/problem.tree.txt) and display it:

```r
library(ggtree)
library(treeio)
t <- read.beast("problem.tree.txt")
ggtree(t)
```

Instead, read.beast() produces a warning:
```
Warning message:
In matrix(x, ncol = 2, byrow = TRUE) :
  data length [9] is not a sub-multiple or multiple of the number of rows [5]
```
and the call to ggtree() results in a segfault.

This problem goes away when the (quoted) spaces are removed from the taxon labels in the NEXUS file.

Apologies if this is a known problem - I couldn't find any mention of this behaviour in previous issues though.

**Comment by xiangpin** [comment]
This might be a bug of ape, I has provided [the pull request](https://github.com/emmanuelparadis/ape/pull/29) to solve the problem.

**Comment by xiangpin** [comment]
This might be a bug of `read.nexus` of `ape`, I have submitted [the pull request](https://github.com/emmanuelparadis/ape/pull/29) the solve the problem.

**Comment by GuangchuangYu** [comment]
fixed in ape now.
